exclude: ^(pkg/grpcdefinition)

repos:
- repo: https://github.com/ansys/pre-commit-hooks
  rev: v0.5.2
  hooks:
  - id: add-license-headers
    args: ["--start_year", "2025"]
    files: '.*\.(py|pyi|proto|go)$'

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files

- repo: local
  hooks:
  - id: go-generate
    name: go generate
    entry: go generate ./pkg/externalfunctions
    language: system
    pass_filenames: false
    stages:
      - pre-commit
    types: [go]
  - id: go-build
    name: go build
    entry: go build ./...
    language: system
    pass_filenames: false
    stages:
      - pre-commit
    types: [go]

- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.0
  hooks:
  - id: go-fmt
  - id: go-imports
  - id: no-go-testing
  # - id: golangci-lint
