# Example configuration file for AALI FlowKit
# This file contains the configuration settings for the AALI system.
# This file is generally expected at the root of the AALI FlowKit repository.
# Replace the values with your own settings as needed.

# Logging settings
###############################
LOG_LEVEL: "debug" # can be "debug", "info", "warning", "error", "fatal"
ERROR_FILE_LOCATION: "error.log" # Location of the error file where fatal errors are logged
# Local logs
LOCAL_LOGS: true # If true, a local log file is created
LOCAL_LOGS_LOCATION: "logs.log" # Location of the local log file
# Datadog logs
DATADOG_LOGS: false # If true, logs are sent to Datadog
LOGGING_URL: "https://http-intake.logs.datadoghq.eu/api/v2/logs" # Datadog URL where logs are sent
LOGGING_API_KEY: "" # Datadog API key
STAGE: "DEV" # Stage of the deployment for logging purposes
VERSION: "1.0.0" # Version of the deployment for logging purposes
SERVICE_NAME: "aali" # Name of the service for logging purposes
DATADOG_SOURCE: "nginx" # Datadog source
# Datadog metrics
DATADOG_METRICS: false # If true, metrics are sent to Datadog
METRICS_URL: "" # Datadog URL where metrics are sent

# SSL Settings
###############################
USE_SSL: false # If true, SSL is used for securing the endpoints exposed by the aali modules
SSL_CERT_PUBLIC_KEY_FILE: "" # Path to the public key file for SSL
SSL_CERT_PRIVATE_KEY_FILE: "" # Path to the private key file for SSL

# Azure Key Vault Settings
###############################
# Instead of using the config.yaml file, most aali modules can extract part of their configuration from Azure Key Vault.
EXTRACT_CONFIG_FROM_AZURE_KEY_VAULT: false # If true, configuration is extracted from Azure Key Vault
AZURE_KEY_VAULT_NAME: "" # Name of the environment variable containing the Azure Key Vault name
AZURE_MANAGED_IDENTITY_ID: "" # Name of the environment variable containing the Azure Managed Identity ID

# Aali Flowkit settings
###############################
FLOWKIT_ADDRESS: "0.0.0.0:50051" # Address where the aali-flowkit listens for incoming requests; for running bare-metal locally, you probably want something like `localhost:50051`; for running in docker, you probably want something like `0.0.0.0:50051`
FLOWKIT_API_KEY: "flowkit-api-key" # API key used by aali-flowkit to secure the endpoint; this key is used to authenticate with the aali-agent
# Aali Modules
LLM_HANDLER_ENDPOINT: "ws://aali-llm:9003" # Endpoint where aali-flowkit connects to aali-llm
# DB connections
GRAPHDB_ADDRESS: "aali-graphdb:8080" # Address of the aali-graphdb; this is used to connect to the graph database
QDRANT_HOST: "qdrant" # Hostname of the Qdrant database; this is used to connect to the Qdrant database
QDRANT_PORT: 6334 # Port of the Qdrant database; this is used to connect to the Qdrant database
