name: Documentation Build

on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true

env:
  MAIN_PYTHON_VERSION: '3.12'

jobs:

  doc-style:
    name: "Documentation style"
    runs-on: ubuntu-latest
    steps:
      - uses: ansys/actions/doc-style@v9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  doc-build:
    name: "Build project documentation"
    runs-on: ubuntu-latest
    needs: [doc-style]
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: Install Python dependencies
        run: |
          pip install -r doc/requirements.txt

      - name: Install GoMarkDoc
        run: |
          go install github.com/princjef/gomarkdoc/cmd/gomarkdoc@latest

      - name: Generate API documentation
        run: |
          cd doc
          make api-docs

      - name: Build HTML documentation
        run: |
          cd doc
          make html

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation-html-with-api
          path: doc/_build/html
